# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
title: Ruben Lopez
email: "rub2106@gmail.com"
description: >
  Full stack web developer, following happy this incredible programming journey!
about_me: >
  I'm a System engineering graduate from San Cristobal de Huamanga University. I got into programming because I love making atomize things, It is beautiful to see how programming can make easy the life, I can work anytime, anywhere with all the latest tools readily available at my fingertips.
baseurl: "" # the subpath of your site, e.g. /blog
url: "rub21.com" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/levytsroman"
twitter_username: "Rub21m"
github_link: "https://www.github.com/Rub21"

select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

# Build settings

markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
